apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-monitoring-grafana
  namespace: monitoring
  labels:
    app: infra-monitoring-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-monitoring-grafana
  template:
    metadata:
      labels:
        app: infra-monitoring-grafana
    spec:
      containers:
        - name: grafana
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: GF_PATHS_CONFIG
              value: /etc/grafana/grafana.ini
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
            # Automatically downloads the VictoriaLogs plugin on startup
            - name: GF_INSTALL_PLUGINS
              value: "victoriametrics-logs-datasource"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: storage
              mountPath: /var/lib/grafana
            - name: config
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
            - name: config
              mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
              subPath: datasources.yaml
            - name: config
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
              subPath: dashboards.yaml
            - name: dashboard
              mountPath: /etc/grafana/provisioning/dashboards/dashboard.json
              subPath: dashboard.json
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.port }}
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: infra-monitoring-grafana
        - name: config
          configMap:
            name: infra-monitoring-grafana-config
        - name: dashboard
          configMap:
            name: infra-monitoring-grafana-dashboard
