image:
  repository: grafana/grafana
  tag: "11.2.0"
  pullPolicy: IfNotPresent

port: 3000

ingress:
  host: grafana.local

storage:
  size: 2Gi
  storageClass: local-path

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

service:
  type: ClusterIP
  port: 80