certificate:
  name: homelab-tls
  namespace: envoy-gateway-system
  dnsNames:
    - "*.local"
    - grafana.local
    - victoriametrics.local
    - victorialogs.local
    - argocd.local
    - testapp.local
  duration: 87600h
  renewBefore: 720h