apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infra-monitoring-victoriametrics
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}