apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-monitoring-victoriametrics
  namespace: argocd
  labels:
    project: infra-monitoring
    component: victoriametrics
spec:
  project: infra-monitoring
  source:
    repoURL: https://github.com/DmytroKrynytsyn/infra-monitoring.git
    targetRevision: HEAD
    path: helm/victoriametrics
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true